version: "3.9"

services:
  media-transcriber:
    container_name: media-transcriber
    image: vihung/personal:media-transcriber
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
      - type: bind
        source: ~/media/inbox
        target: /root/media/inbox
      - type: bind
        source: ~/media/outbox
        target: /root/media/outbox
